# -*- coding: utf-8 -*-
"""MalariaDetection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15-mSjqaqxcSI4wlxPaWgwBO2jTa6Qn6j
"""

#importing libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn import metrics
import joblib

#Step1: Load Dataset
from google.colab import files
uploaded=files.upload()

import io
df = pd.read_csv(io.StringIO(uploaded['dataset.csv'].decode('utf-8')))
# Dataset is now stored in a Pandas Dataframe
print(df.head(5))

#read csv from git
#url = 'https://raw.githubusercontent.com/pooj1277/Malaria-detection/main/dataset.csv'
#df = pd.read_csv(url)
#print(df.head(5))

#Step2: Split into training and test data
x = df.drop(["Label"],axis=1)
y = df["Label"]
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

#Step4: Build a model

model = RandomForestClassifier(n_estimators=100,max_depth=5)
model.fit(x_train,y_train)
joblib.dump(model,"rf_malaria_100_5")

##Step5: Make predictions and get classification report

predictions = model.predict(x_test)

print(metrics.classification_report(predictions,y_test))
print(model.score(x_test,y_test))