# -*- coding: utf-8 -*-
"""Simple_ChatBot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rXKbXZQctt6f4hQLiOO22dVdGXy8wG_8

#ChatBot Program
"""

#import the libraries
from nltk.chat.util import Chat, reflections

pairs = [
    #['my name is (.*)',['hi %1']],
    #['(hi|hello|hey|heya|you there|hola)',['hey there','hi there','heyyy','hi']],
    #['(.*) in (.*) is fun',['%1 in %2 is indeed fun']],
    #['(.*)(location)|city?', ['India','Pune']],
    ['(.*)created you?', ['pooja did using NLTK']],
    ['how is the weather in (.*)', ['the weather in %1 is amazing like always']],
    ['(.*)help(.*)', ['i can help you']],
    ['(.*) your name ?', ['my name is B.O.T']]
]

reflections

dummy_reflections = {
    'go': 'gone',
    'hello' : 'hey there'
}



chat = Chat(pairs, dummy_reflections)
#chat._substitute('you are amazing')
chat.converse()